### ISSUE TITLE
error running Docker image

### ISSUE THREAD

**Issue by erik1474** [flowcommerce/aws-credentials-broker#2]
Keep getting the error

`ERROR: Invalid environment[/usr/local/bin/aws-credentials-broker]. Must be one of: development, production, workstation`

When attempting to run the Docker image - any thoughts on where this is set?  I've looked everywhere...

**Comment by benwaffle** [comment]
The environment variable is `FLOW_ENV=production`

**Comment by benwaffle** [comment]
@grahamar this is a public repo, but we're using our private flowdocker/play and environment-provider. Do we want to package it better for public use?

**Comment by erik1474** [comment]
Thanks...  I had finally got past error that by changing the Dockerfile to:

`ENTRYPOINT ["java", "-jar", "/root/environment-provider.jar", "aws-credentials-broker", "/usr/local/bin/aws-credentials-broker", "production"]`

but good to know the "right" way.  Also, had to tweak the custom schema in utils.go for AWS roles (ours is "SSO" not "AWS_SAML"...)   Last hurdle, I think, is to sort out the /roles api

`[GIN] 2019/02/13 - 04:15:30 | 307 |  330.814271ms |   72.76.179.125 | GET      /oauth/google/callback?state=uVEvqyaJo6PtWBTxJ%2B3jF%2BGL0FqPIgIZm77xYD%2B5RGo%3D&code=4%2F7wCebnMvojS1Spxbn5lKSpG2t0o-Zj7jOsSdYOV1Q_OQ6xxxxxPl3UkQtczZSmImUiWUca7-ZCSUi2att-UI&scope=openid+email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&authuser=0&hd=mydomain.com&session_state=68exxxxcc4eb1a91efc3610cea8d5babed812b13..55c0&prompt=none
Get https://www.googleapis.com/admin/directory/v1/users/gsuite.testuser%40mydomain.com?alt=json&customFieldMask=SSO&projection=custom: oauth2: cannot fetch token: 401 Unauthorized
Response: {
  "error": "unauthorized_client",
  "error_description": "Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested."
}`

**Comment by grahamar** [comment]
@erik1474 @benwaffle apologies for the delay, have updated the repo to use the standard docker images and it's now deployable via Kubernetes.

I'll make the custom field mask configurable too.

Your latest error, looks like you might not have granted the service account client id the scope `https://www.googleapis.com/auth/admin.directory.user.readonly`

**Comment by grahamar** [comment]
You can now use the environment variable `CUSTOM_SCHEMA_KEY` to override the default `AWS_SAML` schema key.

Going to close this, please re-open if you're still having issues 👍
