### ISSUE TITLE
Configurable SAML schema and command-line tool

### ISSUE THREAD

**Issue by nickfishman** [flowcommerce/aws-credentials-broker#4]
Hey @grahamar, a big thank you for releasing this publicly (along with the accompanying [blog post](https://medium.com/flow-tech/aws-api-and-cli-access-for-google-apps-saml-9c67a872c74f)). My team uses Google Apps + AWS and I've been searching for a simple way to streamline the login process for my team. We use several top-level AWS accounts to limit blast radius -- between MFA, the AWS login timeout, and switching between accounts in the console, it's definitely been painful. I also came across a few other solutions that did HTML scraping and was relieved to find the much more sensible approach you've implemented here.

I deployed this earlier and got it working for my team with slight changes. In our case we deployed this to our [Convox](https://convox.com) cluster instead of Kubernetes, and that worked pretty much out of the box.

I did run into a few questions/gotchas:
1) This service assumes that the SAML schema inside Google Apps will use `SessionDuration` and `IAM_role` as field names, respectively. It took me a while to figure out *that* was the reason no roles were being surfaced to the frontend, and adjust our Google Apps schema accordingly. Would it be possible to make these field names configurable via environment variables, similar to how you recently made the top-level schema key configurable with `CUSTOM_SCHEMA_KEY`?

2) Do you have a link to the command-line tool that kicks off the authentication flow and writes the result to `~/.aws/credentials`? I looked around in some of the other repos within `flowcommerce` and couldn't find it.

3) During initial configuration I accidentally put a slash at the end of `ALLOWED_ORIGIN`. This caused the browser's `POST /login` to silently fail with a 403 (presumably because the cors package was failing the request early). This was a bit confusing because it only failed in the case of more than one `IAM_role` returned from Google Apps (in the solo case the server appears to call the login handler implicitly). Would you accept a PR to clarify that this shouldn't contain a trailing slash? That matches the formal definition of the `Origin` header in the RFCs, but I figured it's worth emphasizing since the docs currently refer to it as a URL.

Thanks again for sharing this!

**Comment by grahamar** [comment]
Great to hear it's useful to others @nickfishman 😃 

- I'll look to update so the field names are configurable
- I created a small CLI showcase here - https://github.com/grahamar/belem
- More than welcome to create PRs

Thanks a million for the feedback!
