### ISSUE TITLE
Privilege escalation

### ISSUE THREAD

**Issue by wjordan** [flowcommerce/aws-credentials-broker#6]
I maintain a similar library for providing temporary AWS credentials to Google-federated users at [`code-dot-org/aws-google`](https://github.com/code-dot-org/aws-google), and I was delighted to see a similar approach followed here so I could compare/contrast design details. One key piece that appears to be missing from this setup is restricting the Google Account IDs allowed in the OIDC token granted by Google via the [`accounts.google.com:sub` IAM condition key](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_iam-condition-keys.html#condition-keys-wif), e.g.:

    "Condition": {
      "StringEquals": {
        "accounts.google.com:aud": <our new google client id>
      },
      "ForAnyValue:StringEquals": {
        "accounts.google.com:sub": [
          "<google account id>",
          "<google account id>"
        ]
      }
    }

If I understand the process correctly, without this condition set, it would be possible for any valid account-holder to pass their valid OIDC token to the AWS API directly to gain temporary credentials to _any_ role, including roles they have not been assigned via the SAML process, making it a privilege escalation issue.

**Comment by nscavell** [comment]
@wjordan I was curious about this too, but digging into it more I'm not sure this is true. 

How would a valid account holder get access to an oauth2 token created by the google client/secret configured for the application ? The oauth2 token is encrypted as a cookie and then read by the server to initiate the aws sts call. I don't think the user ever sees this value in transit.

**Comment by wjordan** [comment]
After taking another look I think you're right- I didn't realize the server keeps the `client_secret` hidden from the client and only reveals the `client_id` in its redirect response to the Google oauth2 endpoint. A bad client can't exchange the authorization code it gets from Google for an oauth2 token since that requires both the client id _and_ secret.

My library is a bit different, as a client-only library that doesn't run a server (so the client secret isn't secret) it needs the extra IAM restriction.

Thanks for the help clarifying the design for me!
